apiVersion: apps/v1
kind: Deployment
metadata:
  name: site-sensor-management
  namespace: green-energy-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: site-sensor-management
  template:
    metadata:
      labels:
        app: site-sensor-management
    spec:
      imagePullSecrets:
        - name: nexus-registry-secret
      containers:
        - name: site-sensor-management
          image: nexus-registry.local/com.green.energy.tracker/site-sensor-management:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: site-sensor-management-config
            - secretRef:
                name: site-sensor-management-secret
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "500m"